name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Outras etapas de build, teste, análise estática, etc.

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to production
        run: echo "Deploying to production..."
