name: Page Speed Insights

on:
  push:
    branches:
      - web   # Branch

jobs:
  pagespeed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Page Speed Insights
        uses: JakePartusch/psi-action@v1.3
        with:
          url: https://pedrosalomaodw.github.io/pokesil/  # URL do site
